---
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: end-of-file-fixer
  - id: flake8
    args: ['--ignore=E501']
    language_version: python3.8
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
    - id: black
      name: black
      language: system
      entry: black
      minimum_pre_commit_version: 2.9.2
      require_serial: true
      types_or: [python, pyi]
- repo: git://github.com/Patreon/pre-commit-python-sorter
  rev: 1.0.5
  hooks:
  - id: python-import-sorter
    args:
    - --silent-overwrite
- repo: git://github.com/Patreon/py-ensure-trailing-commas
  rev: v0.2.1
  hooks:
  - id: ensure-trailing-commas
    language_version: python3.8
    args:
    - --auto-fix
    - --report
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.25.0
  hooks:
  - id: yamllint
    args: ["-c", ".yamllint"]
    types: [file]
    files: >
      (?x)^(
        .*\.ya?ml|
        playbooks/group_vars/.*
      )$
- repo: local
  hooks:
  - id: hadolint
    name: Lint Dockerfiles
    description: Runs hadolint to lint Dockerfiles
    language: system
    types: ["dockerfile"]
    entry: hadolint
