name: 'Terrascan IaC scanner'
description: 'Uses Terrascan to detect security violations on Terraform/k8s/Helm/Kustomize files'
inputs:
  changed_only:
    description: 'only parse files that have changed'
    required: false
  config_path:
    description: 'config file path'
    required: false
  debug:
    description: 'print command thats being run'
    required: false
  iac_dir:
    description: 'path to a directory containing one or more IaC files (default ".")'
    required: false
    default: '.'
  iac_type:
    description: 'IaC type (helm, k8s, kustomize, terraform)'
    required: true
  iac_version:
    description: 'IaC version (helm: v3, k8s: v1, kustomize: v3, terraform: v12, v14)'
    required: false
  ignore_path:
    description: 'regex to describe a path to ignore'
    required: false
  only_warn:
    description: 'the action will only warn and not error when violations are found'
    required: false
  policy_path:
    description: 'policy path directory for custom policies'
    required: false
  policy_type:
    description: 'policy type (all, aws, azure, gcp, github, k8s) (default all)'
    required: false
  skip_rules:
    description: 'one or more rules to skip while scanning (example: "ruleID1,ruleID2")'
    required: false
  tag_lines:
    description: 'write the failing rule under the line in the file thats failing'
    required: false
runs:
  using: 'docker'
  image: './Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
