name: Testing

on:
  pull_request:
    branches:
    - main

jobs:
  run_action_warning:
    name: Test action only warn
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        debug: true
        iac_dir: 'test_dirs/fail/'
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true

  run_action_no_issues:
    name: Test run action no issues
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        debug: true
        iac_dir: 'test_dirs/success/'
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true

  run_action_ignore_path:
    name: Test run action to ignore path
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        debug: true
        ignore_path: '^test_dirs/ignore.*'
        iac_dir: '.'
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
